services:
  trip-agency:
    container_name: trip-agency
    restart: always
    image: node:20.10.0
    ports:
      - 3030:3027
    volumes:
      - ./:/usr/src/tripout
    working_dir: /usr/src/tripout

    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "rm -rf dist && npm install && npm run build && npm run start:prod"

  tripout-batch:
    container_name: tripout-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/tripout
    working_dir: /usr/src/tripout
    networks:
      - monorepo-network

    # FOR PRODUCTION
    command: bash -c "npm install && npm run build && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
# nestar-next:  localhost:4000 <=> container:3000
# nestar-api:   localhost:4001 <=> container:3040
# nestar-batch: localhost:4002 <=> container:3008
 